name: mmoClass
version: ${releaseVersion} b${buildNumber}
description: Allow players to have a class system to limit skills, magic, etc.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Class.MMOClass
depend: [Spout, mmoCore]

permissions:
    mmo.class.*:
        default: false
        children:
            mmo.class.self.set: true
            mmo.class.self.change: true
            mmo.class.all.set: true
            mmo.class.all.change: true
    mmo.class.self.set:
        description: Allowed to set their own Class
        default: true
    mmo.class.self.change:
        description: Allowed to change their own Class
        default: op
    mmo.class.all.set:
        description: Allowed to set anyone's Class (including own)
        default: op
    mmo.class.all.change:
        description: Allowed to change anyone's Class (including own)
        default: op
